import os, sys, json5
import meshio
import numpy as np

# ========================================================= #
# ===  code for PHITS-FEM simulation                    === #
# ========================================================= #
#
# --------------------------------------------------------- #
#
#  [INPUT]  
#             * mesh.json      ( need "density" key : [g/cm3] )
#             * model.msh      ( gmsh format )
#  [OUTPUT]
#             * model.bdf      ( NASTRAN large field format )
#
#  [HOWTO]
#             * convert__gmsh2phits( inpFile="model.msh", configFile="mesh.json" )
#       
# --------------------------------------------------------- #
#

# ========================================================= #
# ===  convert__gmsh2phits.py                           === #
# ========================================================= #

def convert__gmsh2phits( mshFile="msh/model.msh", bdfFile="msh/model.bdf", \
                         config=None, configFile="dat/mesh.json", index_plus_1=True ):

    x_, y_, z_ = 0, 1, 2
    
    # ------------------------------------------------- #
    # --- [1] arguments                             --- #
    # ------------------------------------------------- #
    if not( os.path.exists( mshFile ) ):
        raise FileNotFoundError( "[convert__gmsh2phits.py] Cannot Find {}".format( mshFile ) )
    if ( config is None ):
        if ( configFile is None ):
            raise FileNotFoundError( "[convert__gmsh2phits.py] config=?, configFile=? [ERROR]" )
        else:
            with open( configFile, "r" ) as f:
                config = json5.load( f )
            if ( "options" in config ):
                options = config.pop( "options" )
                
    # ------------------------------------------------- #
    # --- [2] load mesh elements & nodes            --- #
    # ------------------------------------------------- #
    import meshio
    print()
    print( "[convert__gmsh2phits.py] loading gmsh file  :: {0}".format( mshFile ) )
    elementType    = "tetra"
    rmesh          = meshio.read( mshFile )
    points         = rmesh.points
    cells          = rmesh.cells_dict[ elementType ]
    cell_data_dict = rmesh.cell_data_dict
    cell_data      = { key:cell_data_dict[key][elementType] for key in cell_data_dict.keys() }
    field_data     = rmesh.field_data
    physNums       = np.array( cell_data["gmsh:physical"] )
    unq, idx       = np.unique( physNums, return_index=True )
    physNums_order = unq[ np.argsort( idx ) ]
    # index          = np.argsort( physNums, kind="stable" )
    # physNums       = physNums[ index ]
    # cells          = cells   [ index ]
    physNums_names = { str( item[0] ):key for key,item in field_data.items() }
    physNums_set   = list( set( [ item[0] for item in field_data.values() ] ) )
    if ( index_plus_1 ):
        cells = cells + 1

    # ------------------------------------------------- #
    # --- [3] Open / Begin Bulk statement           --- #
    # ------------------------------------------------- #
    print( "[convert__gmsh2phits.py] saving nastranFile :: {0}".format( bdfFile ) )
    f = open( bdfFile, "w" )
    f.write( "$ Generated by nkMeshRoutines.convert__gmsh2phits by N.K." + "\n" )
    f.write( "BEGIN BULK" + "\n" )

    # ------------------------------------------------- #
    # --- [4] add GRID Card                         --- #
    # ------------------------------------------------- #
    f.write( "$\n" + "$ GRID cards (nodes)" + "\n" + "$\n" )
    nPoints        = points.shape[0]
    GRID_cards     = np.array( np.repeat( "GRID*   ", nPoints ), dtype=object )
    GRID_continues = np.array( np.repeat( "*       ", nPoints ), dtype=object )
    GRID_returns   = np.array( np.repeat( "\n"      , nPoints ), dtype=object )
    GRID_IDs       = np.arange( nPoints ) + 1
    coord_IDs1     = np.zeros( (nPoints,) )
    coord_IDs2     = np.zeros( (nPoints,) )
    GRID_fmt       = "".join( ["%8s","%16d","%16d","%16.9e","%16.9e","%s","%8s","%16.9e","%16d"] )
    GRID_Data      = np.concatenate( [ GRID_cards[:,None], GRID_IDs[:,None], coord_IDs1[:,None], \
                                       points[:,x_][:,None], points[:,y_][:,None], \
                                       GRID_returns[:,None], GRID_continues[:,None], \
                                       points[:,z_][:,None], coord_IDs2[:,None] ], axis=1 )
    np.savetxt( f, GRID_Data, fmt=GRID_fmt, delimiter="" )

    # ------------------------------------------------- #
    # --- [5] add CTETRA Card                       --- #
    # ------------------------------------------------- #
    f.write( "$\n" + "$ CTETRA cards (elements) " + "\n" + "$\n" )
    nCells       = cells.shape[0]
    CTETRA_cards = np.array( np.repeat( "CTETRA  ", nCells ), dtype=object )
    CTETRA_IDs   = np.arange( nCells ) + 1
    CTETRA_Data  = np.concatenate( [ CTETRA_cards[:,None]   , CTETRA_IDs[:,None], \
                                     physNums[:,None], cells ], axis=1 )
    CTETRA_fmt   = "".join( ["%8s","%8d","%8d","%8d","%8d","%8d","%8d"] )
    np.savetxt( f, CTETRA_Data, fmt=CTETRA_fmt, delimiter="" )
    
    # ------------------------------------------------- #
    # --- [6] add PSOLID Card                       --- #
    # ------------------------------------------------- #
    f.write( "$\n" + "$ PSOLID cards ( Material info ) " + "\n" + "$\n" )
    nPSOLID         = len( physNums_order )
    PSOLID_cards    = np.array( np.repeat( "PSOLID  ", nPSOLID ), dtype=object )
    PSOLID_PIDs     = np.array ( physNums_order    )
    PSOLID_MIDs     = np.arange( 1, nPSOLID+1 )
    PSOLID_coordIDs = np.zeros( (nPSOLID,) )
    PSOLID_fmt      = "".join( ["%8s","%8d","%8d","%8d" ] )
    PSOLID_Data     = np.concatenate( [ PSOLID_cards[:,None], PSOLID_PIDs[:,None], \
                                        PSOLID_MIDs[:,None], PSOLID_coordIDs[:,None] ], axis=1 )
    np.savetxt( f, PSOLID_Data, fmt=PSOLID_fmt, delimiter="" )
    
    # ------------------------------------------------- #
    # --- [] add MAT1 Card                         --- #
    # ------------------------------------------------- #
    f.write( "$\n"+"$ MAT1 cards ( Material Data :: Density ) "+"\n"+"$\n" )
    MAT1_MIDs       = PSOLID_MIDs
    nMAT1           = len( MAT1_MIDs )
    MAT1_cards      = np.array( np.repeat( "MAT1*   ", nMAT1 ), dtype=object )
    MAT1_continues  = np.array( np.repeat( "*       ", nMAT1 ), dtype=object )
    MAT1_returns    = np.array( np.repeat( "\n"      , nMAT1 ), dtype=object )
    MAT1_zeroData1  = np.zeros( (nMAT1,3) )
    MAT1_zeroData2  = np.zeros( (nMAT1,3) )
    keys            = [ physNums_names[str(val)] for val in physNums_order ]
    MAT1_density    = np.array( [ config[key]["density"] for key in keys ] )
    MAT1_Data       = np.concatenate( [ MAT1_cards[:,None], MAT1_MIDs[:,None], \
                                        MAT1_zeroData1, MAT1_returns[:,None], \
                                        MAT1_continues[:,None], MAT1_density[:,None], \
                                        MAT1_zeroData2 ], axis=1 )
    MAT1_fmt        = "".join( ["%8s", "%16d", "%16.9e", "%16.9e", "%16.9e", "%s", \
                                "%8s", "%16.9e", "%16.9e", "%16.9e", "%16.9e" ] )
    np.savetxt( f, MAT1_Data, fmt=MAT1_fmt, delimiter="" )

    # ------------------------------------------------- #
    # --- [7] ENDDATA & Close File                  --- #
    # ------------------------------------------------- #
    f.write( "$\n" + "ENDDATA" + "\n" )
    f.close()
    print()
    return()

    
    

# ========================================================= #
# ===   Execution of Pragram                            === #
# ========================================================= #

if ( __name__=="__main__" ):

    mshFile    = "test/model.msh"
    configFile = "mesh_forSTEP.json"
    convert__gmsh2phits( mshFile=mshFile, configFile=configFile )
